### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by svinkle** [IBMa/Va11yS#184]
Just noticed this error on https://ibma.github.io/Va11yS/WCAG_ARIA/ARIA18_example1.html:

```
Uncaught ReferenceError: $ is not defined at ARIA18_example1.html:11
```

**Comment by marcjohlic** [comment]
Thanks for reporting this!  It looks like we were using http instead of https linking out to jQuery.  I found it in a couple of the other ARIA examples as well.  Changed them to https and also went ahead and switched to Google's CDN.

**Comment by svinkle** [comment]
Glad it was an easy fix. 👍
